import { CategoryProvider } from "./lib/CategoryContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import "./globals.css";
import Main from "./components/Main";
import Home from "./page";
import { ProductProvider } from "@/app/lib/ProductContext";
import React from "react";
import { AuthProvider } from "./lib/AuthContext";
import UserProfile from "./lib/UserInfo";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  auth,
  modal,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
            <NavBar />
            {/* <UserProfile /> */}
            {/* <SheetDemo /> */}
            {children}
        </AuthProvider>
      </body>
    </html>
  );
}
