import { CategoryProvider } from '../lib/CategoryContext';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import NavBar from "./components/NavBar";
import "./globals.css";
import Main from './components/Main';
import Home from './page';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <CategoryProvider>
          <NavBar />
          {children}
        </CategoryProvider>
      </body>
    </html>
  );
}
